// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoomReservationAPI.Data;

#nullable disable

namespace RoomReservationAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209053331_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoomReservationAPI.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Description = "Laboratorium Jaringan Komputer",
                            Location = "Gedung D4 Lt. 3",
                            Name = "C 302"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 60,
                            Description = "Ruang Kelas Gabungan",
                            Location = "Gedung SAW Lt. 6",
                            Name = "06.10"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Description = "Ruang Kelas",
                            Location = "Gedung D3 Lt. 2",
                            Name = "HH.212"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
